// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBORrPlWLhQ0WVNT4z1d4VZT0lQuglshHQ',
    appId: '1:800499116891:web:2b2e063e8002a09d31487e',
    messagingSenderId: '800499116891',
    projectId: 'tugasmobile2-5d4a7',
    authDomain: 'tugasmobile2-5d4a7.firebaseapp.com',
    storageBucket: 'tugasmobile2-5d4a7.firebasestorage.app',
    measurementId: 'G-1E55KS64F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_B051yL29AzFA7JOWUgd1mlFRFR7KUfc',
    appId: '1:800499116891:android:3638cb145df6082a31487e',
    messagingSenderId: '800499116891',
    projectId: 'tugasmobile2-5d4a7',
    storageBucket: 'tugasmobile2-5d4a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ1aSdiuZdVEfZFDF_Bit7seCZb9wgHjA',
    appId: '1:800499116891:ios:41d6bb9881c9b5b831487e',
    messagingSenderId: '800499116891',
    projectId: 'tugasmobile2-5d4a7',
    storageBucket: 'tugasmobile2-5d4a7.firebasestorage.app',
    iosBundleId: 'com.example.mobileTugas2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ1aSdiuZdVEfZFDF_Bit7seCZb9wgHjA',
    appId: '1:800499116891:ios:41d6bb9881c9b5b831487e',
    messagingSenderId: '800499116891',
    projectId: 'tugasmobile2-5d4a7',
    storageBucket: 'tugasmobile2-5d4a7.firebasestorage.app',
    iosBundleId: 'com.example.mobileTugas2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBORrPlWLhQ0WVNT4z1d4VZT0lQuglshHQ',
    appId: '1:800499116891:web:84c5de6dc2d132fa31487e',
    messagingSenderId: '800499116891',
    projectId: 'tugasmobile2-5d4a7',
    authDomain: 'tugasmobile2-5d4a7.firebaseapp.com',
    storageBucket: 'tugasmobile2-5d4a7.firebasestorage.app',
    measurementId: 'G-JWCHLJ2SSV',
  );
}
